branch-defaults:
  default:
    environment: null
    group_suffix: null
environment-defaults:
  zoilome-env:
    branch: null
    repository: null
global:
  application_name: zoilo.me
  branch: null
  default_ec2_keyname: zmercedes
  default_platform: python3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
