# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitelist', '0002_auto_20180228_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
